name: Stickers/Emotes Continuous Delivery
on: push
jobs:
  build-zips:
    name: Build zip packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Upload sticker packs as artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: gura
          path: gura/
  release-zips:
    name: Release zip packages
    runs-on: ubuntu-latest
    needs: build-zips
    steps:
      - name: Download sticker packs as artifacts
        uses: actions/download-artifact@v4
        with:
          name: gura
      - name: Zip this shit up again for some reason
        uses: thedoctor0/zip-release@master
        with:
          filename: gura.zip 
