name: Stickers/Emotes Continuous Delivery
on: push
jobs:
  build-zips:
    name: Build zip packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Upload sticker packs as artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: gura
          path: gura/
  release-zips:
    name: Release zip packages
    runs-on: ubuntu-latest
    needs: build-zips
    steps:
      - name: Download sticker packs as artifacts
        uses: actions/download-artifact@v4
        with:
          name: gura
      - name: Zip this shit up again for some reason
        id: create-zip
        uses: thedoctor0/zip-release@master
        with:
          filename: gura.zip
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: 0.${{ github.run_number }}
          prerelease: true
          files: ${{ steps.create-zip.outputs.upload_url }}
        env:
          GITHUB_REPOSITORY: ron1n/crono-stickerpicker
